site_name: Rhasspy
theme: readthedocs
nav:
  - Home: index.md
  - Install: install.md
  - Services: services.md
  - Tutorials: tutorials.md
  - Reference: reference.md
  - Audio Input: audio-input.md
  - Text to Speech: text-to-speech.md
  - License: license.md
  - About: about.md
