---
name: Deploy

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
        python-version: [3.7]

    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Deploy image
        run: |
          docker login --username rhasspy --password "$DOCKER_PASSWORD"
          scripts/build-docker.sh
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
